[2021-05-11 16:20:39,426] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.create_dim_table 2021-05-11T19:20:33.606802+00:00 [queued]>
[2021-05-11 16:20:39,431] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.create_dim_table 2021-05-11T19:20:33.606802+00:00 [queued]>
[2021-05-11 16:20:39,431] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-11 16:20:39,431] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-11 16:20:39,431] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-11 16:20:39,436] {taskinstance.py:1089} INFO - Executing <Task(ExecuteQueryOperator): create_dim_table> on 2021-05-11T19:20:33.606802+00:00
[2021-05-11 16:20:39,439] {standard_task_runner.py:52} INFO - Started process 98756 to run task
[2021-05-11 16:20:39,445] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'create_dim_table', '2021-05-11T19:20:33.606802+00:00', '--job-id', '69', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmp3yy826z7', '--error-file', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpm5zy84d7']
[2021-05-11 16:20:39,447] {standard_task_runner.py:77} INFO - Job 69: Subtask create_dim_table
[2021-05-11 16:20:39,475] {logging_mixin.py:104} INFO - Running <TaskInstance: etl.create_dim_table 2021-05-11T19:20:33.606802+00:00 [running]> on host 27.2.168.192.in-addr.arpa
[2021-05-11 16:20:39,497] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=etl
AIRFLOW_CTX_TASK_ID=create_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2021-05-11T19:20:33.606802+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-11T19:20:33.606802+00:00
[2021-05-11 16:20:39,498] {execute_query.py:21} INFO - Executing query
[2021-05-11 16:20:39,501] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.caua6g9a7jto.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-05-11 16:20:40,601] {dbapi.py:180} INFO - Running statement: 
    DROP TABLE IF EXISTS forex.dim_active_id; 
    CREATE TABLE IF NOT EXISTS forex.dim_active_id (
    active_id INT,
    active_name TEXT,
    PRIMARY KEY (active_id)
    );
, parameters: None
[2021-05-11 16:20:40,932] {dbapi.py:186} INFO - Rows affected: -1
[2021-05-11 16:20:41,126] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_dim_table, execution_date=20210511T192033, start_date=20210511T192039, end_date=20210511T192041
[2021-05-11 16:20:41,170] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-11 16:20:41,202] {local_task_job.py:146} INFO - Task exited with return code 0
