[2021-05-14 16:43:11,909] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.load_dim_table 2021-05-14T19:43:00.843664+00:00 [queued]>
[2021-05-14 16:43:11,916] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.load_dim_table 2021-05-14T19:43:00.843664+00:00 [queued]>
[2021-05-14 16:43:11,916] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 16:43:11,916] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-14 16:43:11,916] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 16:43:11,923] {taskinstance.py:1089} INFO - Executing <Task(ExecuteQueryOperator): load_dim_table> on 2021-05-14T19:43:00.843664+00:00
[2021-05-14 16:43:11,930] {standard_task_runner.py:52} INFO - Started process 23326 to run task
[2021-05-14 16:43:11,937] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'load_dim_table', '2021-05-14T19:43:00.843664+00:00', '--job-id', '465', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpvzeevaj9', '--error-file', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmp_3lmgy7k']
[2021-05-14 16:43:11,940] {standard_task_runner.py:77} INFO - Job 465: Subtask load_dim_table
[2021-05-14 16:43:11,986] {logging_mixin.py:104} INFO - Running <TaskInstance: etl.load_dim_table 2021-05-14T19:43:00.843664+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-05-14 16:43:12,019] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=etl
AIRFLOW_CTX_TASK_ID=load_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2021-05-14T19:43:00.843664+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-14T19:43:00.843664+00:00
[2021-05-14 16:43:12,021] {execute_query.py:21} INFO - Executing query
[2021-05-14 16:43:12,028] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.caua6g9a7jto.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-05-14 16:43:12,965] {dbapi.py:180} INFO - Running statement: 
    INSERT INTO forex.dim_active_id VALUES
    (1, 'EUR/USD'),
    (2, 'EUR/GBP'),
    (3, 'GBP/JPY'),
    (4, 'EUR/JPY'),
    (5, 'GBP/USD'),
    (6, 'USD/JPY');
, parameters: None
[2021-05-14 16:43:13,254] {dbapi.py:186} INFO - Rows affected: 6
[2021-05-14 16:43:13,435] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=etl, task_id=load_dim_table, execution_date=20210514T194300, start_date=20210514T194311, end_date=20210514T194313
[2021-05-14 16:43:13,482] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-14 16:43:13,493] {local_task_job.py:146} INFO - Task exited with return code 0
