[2021-05-14 19:38:26,135] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.load_dim_table 2021-05-14T22:38:16.731427+00:00 [queued]>
[2021-05-14 19:38:26,141] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.load_dim_table 2021-05-14T22:38:16.731427+00:00 [queued]>
[2021-05-14 19:38:26,141] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 19:38:26,141] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-14 19:38:26,141] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 19:38:26,147] {taskinstance.py:1089} INFO - Executing <Task(ExecuteQueryOperator): load_dim_table> on 2021-05-14T22:38:16.731427+00:00
[2021-05-14 19:38:26,151] {standard_task_runner.py:52} INFO - Started process 25819 to run task
[2021-05-14 19:38:26,158] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'load_dim_table', '2021-05-14T22:38:16.731427+00:00', '--job-id', '571', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmp59v3a_zl', '--error-file', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpkdlp_w7q']
[2021-05-14 19:38:26,159] {standard_task_runner.py:77} INFO - Job 571: Subtask load_dim_table
[2021-05-14 19:38:26,197] {logging_mixin.py:104} INFO - Running <TaskInstance: etl.load_dim_table 2021-05-14T22:38:16.731427+00:00 [running]> on host 27.2.168.192.in-addr.arpa
[2021-05-14 19:38:26,223] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=etl
AIRFLOW_CTX_TASK_ID=load_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2021-05-14T22:38:16.731427+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-14T22:38:16.731427+00:00
[2021-05-14 19:38:26,224] {execute_query.py:21} INFO - Executing query
[2021-05-14 19:38:26,229] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.caua6g9a7jto.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-05-14 19:38:27,350] {dbapi.py:180} INFO - Running statement: 
    INSERT INTO forex.dim_active_id VALUES
    (1, 'EUR/USD'),
    (2, 'EUR/GBP'),
    (3, 'GBP/JPY'),
    (4, 'EUR/JPY'),
    (5, 'GBP/USD'),
    (6, 'USD/JPY');
, parameters: None
[2021-05-14 19:38:27,712] {dbapi.py:186} INFO - Rows affected: 6
[2021-05-14 19:38:27,918] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=etl, task_id=load_dim_table, execution_date=20210514T223816, start_date=20210514T223826, end_date=20210514T223827
[2021-05-14 19:38:27,965] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-14 19:38:27,988] {local_task_job.py:146} INFO - Task exited with return code 0
