[2021-05-14 15:35:50,827] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.create_main_table 2021-05-14T18:35:48.113192+00:00 [queued]>
[2021-05-14 15:35:50,833] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.create_main_table 2021-05-14T18:35:48.113192+00:00 [queued]>
[2021-05-14 15:35:50,833] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 15:35:50,833] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-14 15:35:50,833] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 15:35:50,839] {taskinstance.py:1089} INFO - Executing <Task(ExecuteQueryOperator): create_main_table> on 2021-05-14T18:35:48.113192+00:00
[2021-05-14 15:35:50,842] {standard_task_runner.py:52} INFO - Started process 22115 to run task
[2021-05-14 15:35:50,849] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'create_main_table', '2021-05-14T18:35:48.113192+00:00', '--job-id', '438', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpvs8xom3q', '--error-file', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpns9eymz3']
[2021-05-14 15:35:50,850] {standard_task_runner.py:77} INFO - Job 438: Subtask create_main_table
[2021-05-14 15:35:50,878] {logging_mixin.py:104} INFO - Running <TaskInstance: etl.create_main_table 2021-05-14T18:35:48.113192+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-05-14 15:35:50,899] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=etl
AIRFLOW_CTX_TASK_ID=create_main_table
AIRFLOW_CTX_EXECUTION_DATE=2021-05-14T18:35:48.113192+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-14T18:35:48.113192+00:00
[2021-05-14 15:35:50,899] {execute_query.py:21} INFO - Executing query
[2021-05-14 15:35:50,903] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.caua6g9a7jto.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-05-14 15:35:52,044] {dbapi.py:180} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS forex.binary_options_historical_quotes (
        quote_sk BIGINT IDENTITY (0, 1),
        date_seconds TIMESTAMP,
        active_id INT,
        value NUMERIC (10, 6),
        PRIMARY KEY (quote_sk)
    );
, parameters: None
[2021-05-14 15:35:52,316] {dbapi.py:186} INFO - Rows affected: -1
[2021-05-14 15:35:52,504] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_main_table, execution_date=20210514T183548, start_date=20210514T183550, end_date=20210514T183552
[2021-05-14 15:35:52,547] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-14 15:35:52,561] {local_task_job.py:146} INFO - Task exited with return code 0
