[2021-05-12 19:09:03,528] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.create_dim_table 2021-05-12T21:00:00+00:00 [queued]>
[2021-05-12 19:09:03,533] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.create_dim_table 2021-05-12T21:00:00+00:00 [queued]>
[2021-05-12 19:09:03,533] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-12 19:09:03,533] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-12 19:09:03,533] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-12 19:09:03,538] {taskinstance.py:1089} INFO - Executing <Task(ExecuteQueryOperator): create_dim_table> on 2021-05-12T21:00:00+00:00
[2021-05-12 19:09:03,541] {standard_task_runner.py:52} INFO - Started process 5203 to run task
[2021-05-12 19:09:03,546] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'create_dim_table', '2021-05-12T21:00:00+00:00', '--job-id', '206', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpc1w6y0_r', '--error-file', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmp5ck77eg6']
[2021-05-12 19:09:03,548] {standard_task_runner.py:77} INFO - Job 206: Subtask create_dim_table
[2021-05-12 19:09:03,577] {logging_mixin.py:104} INFO - Running <TaskInstance: etl.create_dim_table 2021-05-12T21:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-05-12 19:09:03,598] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=etl
AIRFLOW_CTX_TASK_ID=create_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T21:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-12T21:00:00+00:00
[2021-05-12 19:09:03,599] {execute_query.py:21} INFO - Executing query
[2021-05-12 19:09:03,604] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.caua6g9a7jto.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-05-12 19:09:05,235] {dbapi.py:180} INFO - Running statement: 
    DROP TABLE IF EXISTS forex.dim_active_id; 
    CREATE TABLE IF NOT EXISTS forex.dim_active_id (
    active_id INT,
    active_name TEXT,
    PRIMARY KEY (active_id)
    );
, parameters: None
[2021-05-12 19:09:05,574] {dbapi.py:186} INFO - Rows affected: -1
[2021-05-12 19:09:05,762] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_dim_table, execution_date=20210512T210000, start_date=20210512T220903, end_date=20210512T220905
[2021-05-12 19:09:05,807] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-12 19:09:05,831] {local_task_job.py:146} INFO - Task exited with return code 0
