[2021-05-15 10:10:37,196] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.remove_s3_files 2021-05-15T04:00:00+00:00 [queued]>
[2021-05-15 10:10:37,200] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.remove_s3_files 2021-05-15T04:00:00+00:00 [queued]>
[2021-05-15 10:10:37,200] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-15 10:10:37,200] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-15 10:10:37,200] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-15 10:10:37,206] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): remove_s3_files> on 2021-05-15T04:00:00+00:00
[2021-05-15 10:10:37,209] {standard_task_runner.py:52} INFO - Started process 27148 to run task
[2021-05-15 10:10:37,215] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'remove_s3_files', '2021-05-15T04:00:00+00:00', '--job-id', '658', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpmi95ijjz', '--error-file', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpautmse9a']
[2021-05-15 10:10:37,217] {standard_task_runner.py:77} INFO - Job 658: Subtask remove_s3_files
[2021-05-15 10:10:37,250] {logging_mixin.py:104} INFO - Running <TaskInstance: etl.remove_s3_files 2021-05-15T04:00:00+00:00 [running]> on host 27.2.168.192.in-addr.arpa
[2021-05-15 10:10:37,275] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=etl
AIRFLOW_CTX_TASK_ID=remove_s3_files
AIRFLOW_CTX_EXECUTION_DATE=2021-05-15T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-15T04:00:00+00:00
[2021-05-15 10:10:40,273] {python.py:118} INFO - Done. Returned value was: None
[2021-05-15 10:10:40,278] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=etl, task_id=remove_s3_files, execution_date=20210515T040000, start_date=20210515T131037, end_date=20210515T131040
[2021-05-15 10:10:40,315] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-15 10:10:40,332] {local_task_job.py:146} INFO - Task exited with return code 0
