[2021-05-14 10:35:55,003] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.create_dim_table 2021-05-14T13:35:48.068959+00:00 [queued]>
[2021-05-14 10:35:55,010] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.create_dim_table 2021-05-14T13:35:48.068959+00:00 [queued]>
[2021-05-14 10:35:55,010] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 10:35:55,010] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-14 10:35:55,010] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-14 10:35:55,016] {taskinstance.py:1089} INFO - Executing <Task(ExecuteQueryOperator): create_dim_table> on 2021-05-14T13:35:48.068959+00:00
[2021-05-14 10:35:55,019] {standard_task_runner.py:52} INFO - Started process 19213 to run task
[2021-05-14 10:35:55,026] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'create_dim_table', '2021-05-14T13:35:48.068959+00:00', '--job-id', '378', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmpgqyphde8', '--error-file', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmp41wasm4g']
[2021-05-14 10:35:55,027] {standard_task_runner.py:77} INFO - Job 378: Subtask create_dim_table
[2021-05-14 10:35:55,063] {logging_mixin.py:104} INFO - Running <TaskInstance: etl.create_dim_table 2021-05-14T13:35:48.068959+00:00 [running]> on host 27.2.168.192.in-addr.arpa
[2021-05-14 10:35:55,087] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=etl
AIRFLOW_CTX_TASK_ID=create_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2021-05-14T13:35:48.068959+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-14T13:35:48.068959+00:00
[2021-05-14 10:35:55,088] {execute_query.py:21} INFO - Executing query
[2021-05-14 10:35:55,094] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.caua6g9a7jto.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-05-14 10:35:56,195] {dbapi.py:180} INFO - Running statement: 
    DROP TABLE IF EXISTS forex.dim_active_id; 
    CREATE TABLE IF NOT EXISTS forex.dim_active_id (
    active_id INT,
    active_name TEXT,
    PRIMARY KEY (active_id)
    );
, parameters: None
[2021-05-14 10:35:56,521] {dbapi.py:186} INFO - Rows affected: -1
[2021-05-14 10:35:56,725] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_dim_table, execution_date=20210514T133548, start_date=20210514T133555, end_date=20210514T133556
[2021-05-14 10:35:56,769] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-14 10:35:56,803] {local_task_job.py:146} INFO - Task exited with return code 0
