[2021-05-16 22:41:49,638] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.create_dim_table 2021-05-17T01:41:43.430521+00:00 [queued]>
[2021-05-16 22:41:49,643] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: etl.create_dim_table 2021-05-17T01:41:43.430521+00:00 [queued]>
[2021-05-16 22:41:49,643] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 22:41:49,643] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-16 22:41:49,644] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 22:41:49,649] {taskinstance.py:1089} INFO - Executing <Task(ExecuteQueryOperator): create_dim_table> on 2021-05-17T01:41:43.430521+00:00
[2021-05-16 22:41:49,652] {standard_task_runner.py:52} INFO - Started process 32857 to run task
[2021-05-16 22:41:49,658] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'create_dim_table', '2021-05-17T01:41:43.430521+00:00', '--job-id', '842', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmp42i9qdb1', '--error-file', '/var/folders/_f/vg3x3jmj23bcz6s88l7v6fb40000gn/T/tmp127pwvyf']
[2021-05-16 22:41:49,659] {standard_task_runner.py:77} INFO - Job 842: Subtask create_dim_table
[2021-05-16 22:41:49,689] {logging_mixin.py:104} INFO - Running <TaskInstance: etl.create_dim_table 2021-05-17T01:41:43.430521+00:00 [running]> on host 27.2.168.192.in-addr.arpa
[2021-05-16 22:41:49,711] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=etl
AIRFLOW_CTX_TASK_ID=create_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2021-05-17T01:41:43.430521+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-17T01:41:43.430521+00:00
[2021-05-16 22:41:49,712] {execute_query.py:21} INFO - Executing query
[2021-05-16 22:41:49,715] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.caua6g9a7jto.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-05-16 22:41:50,769] {dbapi.py:180} INFO - Running statement: 
    DROP TABLE IF EXISTS forex.dim_active_id; 
    CREATE TABLE IF NOT EXISTS forex.dim_active_id (
    active_id INT,
    active_name TEXT,
    PRIMARY KEY (active_id)
    );
, parameters: None
[2021-05-16 22:41:51,079] {dbapi.py:186} INFO - Rows affected: -1
[2021-05-16 22:41:51,259] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_dim_table, execution_date=20210517T014143, start_date=20210517T014149, end_date=20210517T014151
[2021-05-16 22:41:51,318] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-16 22:41:51,370] {local_task_job.py:146} INFO - Task exited with return code 0
